language: cpp

compiler: gcc

branches:
    only:
        - master

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -y -qq
install:
# g++4.8.1
    - sudo apt-get install -y -qq g++-4.8 gcc-4.8
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
    - g++ --version
    - gcc --version
    - ./script/get-linux-deps.sh
script: mkdir -p build && cd build && cmake -D CMAKE_COLOR_MAKEFILE=OFF .. && make && ./test/testga
