language: cpp

compiler: gcc

branches:
    only:
        - master

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
install:
# g++4.8.1
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"
    - $CXX --version
    - ./script/get-linux-deps.sh
script: mkdir -p build && cd build && cmake -D CMAKE_COLOR_MAKEFILE=OFF .. && make && ./test/testga
